/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "./extensions";
export type { extensions };
import type * as presets from "./presets";
export type { presets };
export type { Raffle } from "./Raffle";
